### ISSUE TITLE
conntrack_exporter for windows

### ISSUE THREAD

**Issue by MatzeP** [hiveco/conntrack_exporter#11]
Hi,
you have exactly what I search.

Did you have also Version for Windows Server?

Docker I can't run on the server. 

Thanks

**Comment by dbendelman** [comment]
Hi @MatzeP, sorry I didn’t get notifications from this repo and hadn’t stumbled into your issue until now.

This exporter exposes the Linux connection table. I think you’ll have to find/write a whole new exporter for Windows since the two operating systems have totally different networking internals.
